/** Declaration file generated by dts-gen */


export interface TextResult {
    text: string
    lineNum: number
}

export interface CommandResult {
    name: string
    args: string[]
    result: any
}

export interface OptionsResult {
    options: string[]
    lineNum: number
    selected: number
    select(index: number): void
}
export type BondageResults = OptionsResult | TextResult | CommandResult

export class Runner {
    constructor();

    evalNodes(...args: any[]): void;

    evaluateAssignment(...args: any[]): void;

    evaluateConditional(...args: any[]): void;

    evaluateExpressionOrLiteral(...args: any[]): void;

    handleSelections(...args: any[]): void;

    load(...args: any[]): void;

    registerFunction(key: string, func: Function): void;

    run(node: string): Generator<BondageResults,BondageResults,undefined>;

    setVariableStorage(...args: any[]): void;

}
