packages:
    # all packages in direct subdirs of packages/
    - "packages/api"
    - "packages/big-other"
    - "packages/dialogue"
    - "packages/gravispats"
    - "packages/joegamelib"
    - "packages/mapscripts"
    - "packages/midi"
    - "packages/noise"
    - "packages/poker"
    - "packages/scrapers"
    - "packages/tiled-extensions"
    - "packages/timidity"
    - "packages/twitterbot"
    - "packages/web-tape"
    - "packages/world-lisp"
    - "packages/wr-ts"
    - "apps/*"
    - "site"
    - "test/"
    - "assets"
