#+TITLE: Preliminaries
* It can be whatever
#+begin_epigraph
#+begin_quote
The coming being is whatever being.
#+end_quote
#+begin_footer
Giorgio Agamben, /The Coming Community/
#+end_footer
#+end_epigraph
We need to not waste time, need to be /in/ this as soon as possible.  As soon as we commit to this, a latency will be created.  Between the reading part and the code part.  Between the game as it is only right now /conceived/ and the things we can talk about.  Or, lets be even more simple: what is this place, where the words are placed?  It is, at least, three things:
1. For me, right now, it is in what is called a buffer, sitting in a window, in the software application GNU Emacs.  The buffer is the place where text can be added and removed, and whenever I want I can choose to "write" the text to a file.
2. For you, right now, it is within a paragraph =<p>= tag, in a semantic =<section>= tag, which is in the =<article>= which is in the =<body>= which resides in a HTML file that is stored on some computer that was called out to when your browser went to this site.
3.  For the computer, in part, this exists as a file in the "source tree" that my version control software is vaguely aware of as particular sequence of bytes.

These differing dimensions of the text can have far reaching consequences.  In between 1 and 2 is a /compilation/, in between 3 and 1 (and by extension 2) is the sporadic intervals of artificial history that "version control" creates.

In truth, much of the magic we will try and cultivate here is based in the "compilation" step.  This is because the text we are writing is not merely within Emacs, but in the arcane protocol of "Org mode" which provides a number of useful tools to form a world.  What it provides is simply this: a syntax and grammar for writing human text and computer text ("code").  A period signifies the end of sentence, and words within quotation express some kind of indirection, and in Org mode, a single asterisk at the beginning of a line signifies a top-level heading, and words contained within "blocks" can express "functions" that can affect the final output of the html page that is hosted and you are viewing.  Blocks can at once be files, or they can provide functionality.

The aim of the joegame dev log dungeon is to /use/ some of these tools to help me finish a video game.  Already though, the dev log threatens to consume the game itself, where the game is nothing more but a an outgrowth of the log.  This though, is merely an intesification of the earlier duality of the joegame and the website.  Really, we are making a website, despite doing it in a fairly convoluted way.

Obviously, we are writing.  Whether it is this text right now or something that looks more like "code," we are writing.  Why is it so different?  In the /Phaedrus/ the threat of writing is the threat of patricide.  For computer code, the threat is more villainous because it never needs a father.
* Teaching piano
When you are first teaching a child to play the piano, you sit them down on the bench and say: "for the piano, /this/ is down" while you gesture to the left end of the keys, emphasizing both 'this' and 'down,' and then you say, "and /this/ is up!"  Like most true learning, the information arrives as an analogy to something that is already known; the effort of teaching is to get the student to take one ready-to-go schema and overlay it over something else that is otherwise blank.  At a certain point, rather quickly in this example, you can "kick away the ladder" and the orientation of the keyboard  can stand on its own, but it is only temporary, because a little after this you need to establish with them on another level why this orientation matters, namely the ordinal nature of pitch, and the sense's that correlate whether you go one direction or another on the ordered pitches.  You tell them: "this is /LOW/" as you strike A1, "and this is /HIGH/" as you move 5 octaves up to hit the A5.  But this isn't the same thing as before: there is no analogy here, you are merely labeling the sounds src_sidenote(Really\, if we were trying to explain the situation with a correlation\, we would say that this part is "slower" and this part "faster" and attempt to show the perceptible string oscillation of the former.  This would confuse the student later on thought\, when you discuss tempo.).  Regardless, once this is established, you can move on all the same.

This all could happen differently though.  The "down" of the piano is really its left side after all, and the "lowness" of a pitch can't be derived as such without proper experimentation.  The kid could just find the piano after all, abandoned, off of some hall.  They could touch the keys and experience the movement itself from low to high.  They would naturally arrive much more quickly to considerations of harmony, as with multiple fingers and two hands you are more likely to try pushing two keys at once.

In truth, what Jacques Rancière calls the "the logic of the explicative system" that underlies our pedagogical values is one where the teacher/master has as much to gain as the ignorant student, if not more:
#+begin_quote
Explication is not necessary to remedy the incapacity to understand.  On the contrary, that very incapacity provides the structuring fiction of the explicative conception of the world.  It is the explicator who needs the incapable and not the other way around; it is he who constitutes the incapable as such.  To explain something to someone is first of all to show him he cannot understand it by himself.  Before being the act of the pedagogue, explication is the myth of pedagogy, the parable of a world divided into knowing minds and ignorant ones, ripe minds and immature ones, the capable and the incapable, the intelligent and the stupid. (/The Ignorant Schoolmaster/ p. 6)
#+end_quote
There is the piano you see first, one you can touch.  Before long, I come over and say: "What you think this is right here is not, I will tell you."  Once the words are spoken, the student undergoes more transformations than their mind will during the course of the lesson: beyond what they may take away from the lesson, what they have gained a place within a historically rigid constellation of master and pupil, the one who knows and the stupid one.

As goes the internet.  Its dull roar.

* A few distinctions
